Application.put_env(:wise_gpt_ex, :openai_api_key, "sk-XXX")
Application.put_env(:wise_gpt_ex, :anthropic_api_key, "sk-ant-api-XXX")
Application.put_env(:wise_gpt_ex, :mistral_api_key, "XXX")
Application.put_env(:wise_gpt_ex, :groq_api_key, "XXX")
ExUnit.start()
