Mox.defmock(HTTPoison.BaseMock, for: HTTPoison.Base)
Application.put_env(:wise_gpt_ex, :http_client, HTTPoison.BaseMock)
Application.put_env(:wise_gpt_ex, :openai_api_key, "sk-XXX")
Application.put_env(:wise_gpt_ex, :anthropic_api_key, "sk-ant-api-XXX")
ExUnit.start()
